name: 最新データをダウンロード

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 10 * * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://covid-19-surveillance.s3-ap-northeast-1.amazonaws.com/public_data/covid-19_daily_survey.csv > public/data/data.csv
        TZ=JST-9 date "+%Y-%m-%d" > public/data/timestamp.txt
    - name: Commit and push if it changed
      run: |-
        git config user.name "shimizu"
        git config user.email "xxshimizuxx@gmail.com"
        git add -A
        timestamp=$(TZ=JST-9 date "+%Y-%m-%d %H:%M")
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
